### ISSUE TITLE
jest-vue-matcher

### ISSUE THREAD

**Issue by 14nrv** [mwangaben/mwangaben-vthelpers#20]
Hi,

I just published on npm : [jest-vue-matcher](https://github.com/14nrv/jest-vue-matcher)
It have the same matchers as this package but we can use the .not for the reverse matcher :)

So, for example, instead of 
```
b.domHas('h2')
b.domHasNot('h6')
```

We can use:
```
expect('h2').toBeADomElement()
expect('h6').not.toBeADomElement()
```

Feel free to give feedback

**Comment by mwangaben** [comment]
It is nice idea, it reads like a natural language for example expect('h2').toBeADomElement() ,which makes  it easy to know what you are really testing
